---
- name: Install K3s on Master Node
  hosts: docker_hosts_master
  become: true

  tasks:
  - name: Add memory cgroup to /boot/cmdline.txt
    shell: sed -i 's/rootwait/rootwait cgroup_memory=1 cgroup_enable=memory/' /boot/cmdline.txt

  - name: Restart Master Node
    reboot:

  - name: Wait for the Master Node to come back online
    wait_for_connection:
      delay: 10

  - name: Update System
    apt:
      update_cache: yes
      upgrade: yes

  - name: Restart Master Node
    reboot:

  - name: Wait for the Master Node to come back online
    wait_for_connection:
      delay: 10

  - name: Install K3s
    shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_NODE_NAME="master" sh -

  - name: Get node-token file
    ansible.builtin.fetch:
      src: /var/lib/rancher/k3s/server/node-token
      dest: ./
      flat: yes

  - name: Restart Master Node
    reboot:

  - name: Wait for the Master Node to come back online
    wait_for_connection:
      delay: 10

- name: Install K3s on Slave Nodes
  hosts: docker_hosts_slaves
  become: true
  gather_facts: yes
  vars:
    local_file_path: "./node-token"
  tasks:
  - name: Read node-token file
    set_fact:
      token: "{{ lookup('file', local_file_path) }}"

  - name: Add memory cgroup to /boot/cmdline.txt
    shell: sed -i 's/rootwait/rootwait cgroup_memory=1 cgroup_enable=memory/' /boot/cmdline.txt

  - name: Restart Slave Nodes
    reboot:

  - name: Wait for the Slave Nodes to come back online
    wait_for_connection:
      delay: 10

  - name: Update System
    apt:
      update_cache: yes
      upgrade: yes

  - name: Restart Master Node
    reboot:

  - name: Wait for the Master Node to come back online
    wait_for_connection:
      delay: 10

  - name: Install K3s
    shell: curl -sfL https://get.k3s.io | K3S_TOKEN="{{ token }}" K3S_URL="https://{{ hostvars[groups['docker_hosts_master'][0]]['inventory_hostname'] }}:6443" K3S_NODE_NAME="{{ ansible_hostname }}" sh -

  - name: Restart Slave Nodes
    reboot:

  - name: Wait for the Slave Nodes to come back online
    wait_for_connection:
      delay: 10
