---
- name: Restart Cluster playbook
  hosts: docker_hosts
  become: true
  tasks:
    - name: Restart Master Node
      reboot:

    - name: Wait for the Master Node to come back online
      wait_for_connection:
        delay: 10
